### PR TITLE
Implement SafeLock controller

### PR DESCRIPTION
**Pull request by orkunkl**
I've come across the usage of this logic a few times. Thought would be good to have it in cw-plus.
Not sure about the naming though. Maybe `KillSwitch`, `SafetyLock`?

### CODE REVIEW

**Comment by ethanfrey** [comment]
This is so simpler, I don't really see the need as is.
Combining it with some logic for authorising this (eg admin) would make more sense to me.

Curious to see a link to a few pieces of code that do use it.

**Comment by orkunkl** [comment]
I've seen this use in Loterra contract and nft-marketplace contract that I implement. I think having a safety lock in the first stages make sense.

**Comment by ethanfrey** [comment]
> I've seen this use in Loterra contract and nft-marketplace contract that I implement. I think having a safety lock in the first stages make sense.

I agree with the use of some safety lock. I think the code extracted here is so small, it doesn't really warrant extraction.

I would look at the whole logic of the other contracts and extract a little bigger piece out. Like maybe wrapping an Admin as well, so this handles auth checks as well.

`let is_enabled = self.0.load(deps.storage)?` doesn't really warrant a type and a method in my mind.

**Comment by ethanfrey** [comment]
Maybe just documenting the pattern is enough here.

Controllers should have enough logic on top of the Map to make it meaningful for reuse

**Comment by orkunkl** [comment]
Agree with you on the simple part. I wanted to leave the authorization part to the developer, to provide flexible usage.

**Comment by ethanfrey** [comment]
This is just an `Item<bool>` with some explanation.
I would just add some docs on the usage, not some type.

**Comment by orkunkl** [comment]
Cool closing the PR.

**Pull request closed without merging**
