### PR TITLE
Handle duplicate members in cw4-group create

### PR DESCRIPTION
**Pull request by codehans**
When a cw4-group contract is instantiated with a list of members where some are duplicated, the iterator overwrites any previous member weight, whilst still incrementing the total weight. This PR merges duplicate weights in the `create` function

### CODE REVIEW

**Comment by ueco-jb** [comment]
@codehans will you pick up that PR and add some proper test?

**Comment by ezekiiel** [comment]
fwiw - i do think this could be considered to be a non-backwards compatible change.

for example, before [our audit](https://github.com/oak-security/audit-reports/blob/master/DAO%20DAO/2022-06-22%20Audit%20Report%20-%20DAO%20DAO%20v1.0.pdf) (see the first issue there) we did not dedup the members list when instantiating a dao that uses cw4-groups. we [now do](https://github.com/DA0-DA0/dao-contracts/blob/693a5d6a36ada1505c5a52e8029b1b80ea557393/contracts/cw4-voting/src/contract.rs#L30-L38), but were this to land we'd probably stop doing that to be consistent with the new behavior.

**Comment by codehans** [comment]
apologies @ueco-jb @ezekiiel missed this one. this isn't something we're actively using or particularly precious about. happy to leave as-is, especially as time is fairly scarce these days

**Comment by uint** [comment]
This looks like a serious flaw. If you don't mind, I'll pick this up, rebase, add a test, and merge. @codehans do you mind if I push here?

**Comment by uint** [comment]
> fwiw - i do think this could be considered to be a non-backwards compatible change.

@0xekez That's fair! I don't think we guarantee backwards-compatibility currently (`0.*` semantic versions). Is this going to cause problems for you?

**Comment by codehans** [comment]
> This looks like a serious flaw. If you don't mind, I'll pick this up, rebase, add a test, and merge. @codehans do you mind if I push here?

go ahead!

**Comment by uint** [comment]
@codehans Would you mind signing the CLA thing? I'll need that to merge later.

**Review by ethanfrey — APPROVED** [review]
lgtm with error on duplicates

**Pull request merged**
