### PR TITLE
Make cw721-base queries public

### PR DESCRIPTION
**Pull request by maurolacy**
On behalf of @shanev.

Closes / replaces #397.

### CODE REVIEW

**Comment by maurolacy** [comment]
`vw-plus` contracts are more or less split in that they make these internal query functions public:

```bash
$ grep "fn query_" contracts/*/src/contract.rs | grep ":pub" | wc -l
28
$ grep "fn query_" contracts/*/src/contract.rs | grep -v ":pub" | wc -l
26
$ 
```

So, I would say, this is perhaps not best practice, but it's OK / allowed.

**Comment by shanev** [comment]
@maurolacy What's the case against making all query functions public?

**Comment by maurolacy** [comment]
> @maurolacy What's the case against making all query functions public?

None, really. It's just that it's supposed these functions must be called through the `query` handler. But as you said, it's pretty convenient for tests. And making them public is not a risk, because they cannot be called directly in a production environment anyway.

**Comment by ethanfrey** [comment]
> > @maurolacy What's the case against making all query functions public?
> 
> None, really. It's just that it's supposed these functions must be called through the `query` handler. But as you said, it's pretty convenient for tests. And making them public is not a risk, because they cannot be called directly in a production environment anyway.

Nice fix.

I'm fine to make them all public. I was trying not to expose everything  but you do need all the execute* and query* functions to be public to extend a contract, so why not do that everywhere just in case someone wants to extend it?

**Pull request merged**
