### PR TITLE
Align tests to mock_dependencies changes

### PR DESCRIPTION
**Pull request by hashedone**
The `mock_dependencies` function was changed in breaking way, but semver-compatible version was set after the change, which made most test not compile after removing `Cargo.lock` (or doing some change which would make update it). This aligns tests to work with those changes.

### CODE REVIEW

**Review by ueco-jb — APPROVED** [review]
Not all heroes wear capes.

Also, you forgot to run schema.

**Comment by hashedone** [comment]
Ah, forgot schema. Will come back to this little bit later and then merge with proper schemas.

**Review by webmaster128 — APPROVED** [review]
LGTM.

I recommend never removing Cargo.lock completely to avoid dealing with all kind of unrealated changes at once (here schemars upgrade). You can delete the blocks you care about and let cargo repait the file.

**Comment by hashedone** [comment]
@webmaster128 I absolutely disagree. If semver is properly used there would never be this kind of a problem. Therefore I would say - you should always remove your `Cargo.lock` before your final commit to make sure, you didn't mess up the world around.

The official recommendation is to keep `Cargo.lock` committed for binaries to avoid unknown bugs in non-breaking-changes of your binary dependency assuming, that binary might have additional manual integration done besides CI testing, and nothing should update the dependencies (even non-breaking) without such integration. But for library crates the recommendation is to never commit the `Cargo.lock`, as library should build and work with any version of dependencies, and the final dependencies should be determined by binary using it.

In this very case I had to update the failing dependency anyway so it won't make a difference.

**Comment by webmaster128** [comment]
Feel free to disagree. But you are missing a bunch of practical aspects here:
- In semver anything can break at any time in 0.x and pre-releases. So you must not use any of those dependencies.
- It's not even clear what breakage means. Is a different schemars output breaking? Well, here it clearly causes a diff worth thinking about.
- Deleting the lockfile makes the diff almost impossible to read. Nobody will look at the changes anymore.
- You create merge conflicts.
- Not checking in lockfiles for libraries created non-deterministic CI builds, which is very annoying if you try to hunt down a problem.

**Comment by webmaster128** [comment]
If the delete & repair flow bothers you (which works perfectly well for both cargo any yarn), you can use the upgrade commands of cargo as well.

**Pull request merged**
