### PR TITLE
Properly handle generic queries in multi-test

### PR DESCRIPTION
**Pull request by ethanfrey**
Make ContractWrapper::new_with_empty convert Deps<Empty> to Deps<Q>

### CODE REVIEW

**Comment by ethanfrey** [comment]
@maurolacy this is a start.
fails due to lifetime issue that may require a change  to cosmwasm-std

**Comment by maurolacy** [comment]
Will give it a try tomorrow. Ended up avoiding the need for this by removing the custom message from `tg4-group` entirely. See https://github.com/confio/poe-contracts/pull/109.

**Comment by maurolacy** [comment]
Trying this, but needs to do an upgrade of dependencies / patches locally to properly assess it works.

That said, I think this is a good idea, and we should merge this, after confirming it works, or making the needed changes.

**Review by ueco-jb — APPROVED** [review]
LGTM
I think this is a way to go.
I only wonder, is this change breaking? From generic type to concrete (`Empty`) one?

**Review by uint — APPROVED** [review]
Seems good enough!

**Comment by ethanfrey** [comment]
> I only wonder, is this change breaking? From generic type to concrete (Empty) one?

In theory, but everyone using `Response<Empty>` is also using `Deps<Empty>`
If there are some using `Response<T>` with `Deps<Empty>` or `Response<Empty>` with `Deps<T>` that will be breaking.

Maybe we can add two extra functions for those two (less likely cases). I am sure they will pop up eventually

**Comment by ethanfrey** [comment]
> Anyway: I have a strong feeling that the message type (custom or empty) should be orthogonal to the multi-test blockchain / app. And that we are running into all these clashes, in the end, because it isn't.

It would be much easier if they were. But I think they cannot be.

Basically, we need to ensure the Response returned is a subset of the possible responses managed by the app.
And the Querier needed is a subset of the Querier provided.

The other option is just use `Vec<u8>` everywhere, but we couldn't even parse the Response from a contract without knowing the Custom type

**Comment by ethanfrey** [comment]
Can you make a PR to the case you mention that *almost* works and I will look into it?

**Comment by ethanfrey** [comment]
I would like to:

1. Improve multi-test generics enough to make this work well for now.
2. Later, make multi-test more robust / easy to use

**Comment by maurolacy** [comment]
> Can you make a PR to the case you mention that _almost_ works and I will look into it?

There you go: https://github.com/confio/tfi/pull/68

**Comment by maurolacy** [comment]
> > Anyway: I have a strong feeling that the message type (custom or empty) should be orthogonal to the multi-test blockchain / app. And that we are running into all these clashes, in the end, because it isn't.
> 
> It would be much easier if they were. But I think they cannot be.
> 
> Basically, we need to ensure the Response returned is a subset of the possible responses managed by the app. And the Querier needed is a subset of the Querier provided.
> 
> The other option is just use `Vec<u8>` everywhere, but we couldn't even parse the Response from a contract without knowing the Custom type

Can't we define the message type at the calls / `store_code`, etc. levels? Instead of having everything pre-defined as `Empty` or some custom type at the `App` level.

It's a matter of decoupling the message type from the app. I understand it will require some major overhauling, though.

**Comment by ethanfrey** [comment]
The issue is the App has a custom module (not contract) that can handle custom messages C and queries Q.

The contracts must all return C or Empty so they can be dispatched.

**Comment by maurolacy** [comment]
I see. Some thoughts or ideas that come to mind:

- Use serialisation / deserialisation tricks to handle / dispatch multiple message types internally. Everyone knows what to expect / receive, so it just optimistically tries to deserialise to it.
- Instead of a `Custom(T)` enum, use the / a `CustomMessage` trait to abstract away different message types, and `dyn` our way around it. Not sure we can have something like a `Custom(dyn CustomMessage)`, but you get the idea.

These are just off the top of my head. I don't know how relevant / practical / possible / sensible they are.

**Pull request merged**
