### PR TITLE
Move test helpers into a test section

### LINKED ISSUE #708: Test-specific helpers in storage-plus
`mod.rs` in `storage-plus/src/indexes` contains what appears to be test helpers:

```rs
pub fn index_string(data: &str) -> Vec<u8> {
    data.as_bytes().to_vec()
}

pub fn index_tuple(name: &str, age: u32) -> (Vec<u8>, u32) {
    (index_string(name), age)
}

pub fn index_triple(name: &str, age: u32, pk: Vec<u8>) -> (Vec<u8>, u32, Vec<u8>) {
    (index_string(name), age, pk)
}

pub fn index_string_tuple(data1: &str, data2: &str) -> (Vec<u8>, Vec<u8>) {
    (index_string(data1), index_string(data2))
}
```

Maybe the test-specific parameters like `age` could use better names? Or maybe this code doesn't belong here?

### PR DESCRIPTION
**Pull request by shanev**
Fixes #708.

### CODE REVIEW

**Review by ueco-jb — APPROVED** [review]
LGTM

**Comment by ueco-jb** [comment]
@shanev Hey, can you update that PR and merge it?

**Comment by shanev** [comment]
@ueco-jb I don't have merge powers. Wanna make me a contributer? Happy to review PRs and help out.

**Comment by ueco-jb** [comment]
@shanev Hmm, I see you are already a member of CosmWasm organization. I think you should clarify that with @webmaster128.

**Pull request merged**
