### PR TITLE
Make cw4-group queries public

### PR DESCRIPTION
**Pull request by shanev**
This allows this contract to be extended, including the queries.

Note: Should the version be incremented?

### CODE REVIEW

**Review by ueco-jb — APPROVED** [review]
I guess there's no harm in that.

> Should the version be incremented?

Version of what, the contract? It's updated when we're releasing new version of whole `cw-plus`.

**Review by webmaster128 — COMMENTED** [review]
Can you show how you use this? Making all those internals public is not great IMO. It will make it hard to impossible to do contract internal cleanups like fixing the naming inconsistency between `fn query_member` and `fn list_members`.

Can you go through `query` instead?

**Review by webmaster128 — COMMENTED** [review]
Okay, let's go with the flow. Can you add the missing `query_` prefix to `list_members`, then merge?

**Comment by ismellike** [comment]
This has been resolved
https://github.com/CosmWasm/cw-plus/pull/802

**Comment by uint** [comment]
Closing, see above comment

**Pull request closed without merging**
